name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  qodana:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["222", "223", "231"]
    
    steps:
      - uses: actions/checkout@v3

      # You can avoid this step if you already have the config files in your repo
      - name: Get configs
        run: |
          wget https://raw.githubusercontent.com/pontem-network/qodana-move/main/config/qodana-inspections-profile.xml
          wget https://raw.githubusercontent.com/pontem-network/qodana-move/main/config/qodana.yaml
          echo "linter: ghcr.io/pontem-network/qodana-move:${{ matrix.version }}" >> qodana.yaml
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}